class ResponseMessages():
    REQUIRES_USERNAME = 'REQUIRES USERNAME: 아이디가 필요합니다.'
    USER_NOT_FOUND = 'USER NOT FOUND: 회원을 찾을 수 없습니다.'

    FCM_TOKEN_REGISTER = 'FCM TOKEN REGISTER: FCM 토큰이 성공적으로 등록되었습니다'
    REQUIRES_FCM_TOKEN = 'REQUIRES FCM TOKEN: FCM 토큰이 필요합니다.'

    FOLLOW_CREATE_SUCCESS = 'FOLLOW CREATE SUCCESS: 팔로우에 성공하였습니다.'
    FOLLOW_DELETE_SUCCESS = 'FOLLOW DELETE SUCCESS: 언팔로우에 성공하였습니다.'
    FOLLOWER_DELETE_SUCCESS = 'FOLLOWER DELETE SUCCESS: 팔로워 삭제에 성공했습니다.'

    READ_NOTIFICATION = 'READ NOTIFICATION: 알림을 모두 읽음 처리하였습니다.'